### ISSUE TITLE
Duct.jl Postprocessing Error

### ISSUE THREAD

**Issue by inse0918** [byuflowlab/FLOWPanel.jl#12]
Hi, Ed.

I firstly use it. And your 3D Panel method looks good. Thank You.

The error is under.

![image](https://github.com/byuflowlab/FLOWPanel.jl/assets/93040154/ac3c628c-5a25-44e7-a148-c29015ffd061)
![image](https://github.com/byuflowlab/FLOWPanel.jl/assets/93040154/2c08c5a4-6e5c-4d65-8a67-d978e962bdac)
![image](https://github.com/byuflowlab/FLOWPanel.jl/assets/93040154/7b779fd4-5d04-4521-a36b-0ec2a4b626a2)

The issue is the results that I ran is not same with the validation data that you uploaded.

![image](https://github.com/byuflowlab/FLOWPanel.jl/assets/93040154/b95c4e95-6da7-4b00-bc9d-f8087c03fc54)

How can I make the result like you ?

Thank you.
Best regards,
Inseo.

**Comment by agrewalks** [comment]
Hi Eduardo,
I have the same issue as Inseo.  I am using the following branch of FLOWPanel: https://github.com/byuflowlab/FLOWPanel.jl/tree/compathelper/new_version/2023-07-06-00-25-31-003-00199311620
and do not get the results that are shown in the examples section or the ones given in your recent aviation forum paper. 
Regards
Anant Grewal

**Comment by EdoAlvarezR** [comment]
Thanks for pointing this out, Inseo and Anant! In an older version of FLOWPanel we were calculating the surface velocity proved at an arbitrary offset from the surface. Later we implemented the Green-Gauss gradient method to compute the surface velocity, which gives the results reported in the AVIATION paper.

I didn't get to update any of the examples to reflect that change until now. 

Before:
```julia
Us = pnl.calcfield_U(body, body, offset=0.03, characteristiclength=(args...)->d*aspectratio)
```
Now:
```julia
Us = pnl.calcfield_U(body, body, characteristiclength=(args...)->d*aspectratio)
```

With that change, you should now be getting the following results:
![image](https://github.com/byuflowlab/FLOWPanel.jl/assets/14857108/6fb8c2c0-511f-48e9-abcc-561fa306fc6e)
![image](https://github.com/byuflowlab/FLOWPanel.jl/assets/14857108/2d4e8c64-db4c-4930-812e-d31288b339a4)
![image](https://github.com/byuflowlab/FLOWPanel.jl/assets/14857108/07b63db8-6bbb-4ca5-8aef-acd75fcf2781)


The examples have been updated. We also merged the branch with the Green-Gauss method into main and released a new version: [github.com/byuflowlab/FLOWPanel.jl/releases](https://github.com/byuflowlab/FLOWPanel.jl/releases). I should warn you that, even though the Green-Gauss method improves the calculation of the surface velocity quite a bit while being consistent with the theory, we haven't been able to get the scheme to work well at discontinuities in the geometry (like open edges and trailing edge), so expect spurious results at edges. We hope to solve this as we continue developing FLOWPanel (or, if you would like to tackle that issue, we would greatly appreciate it =] ).

**Comment by EdoAlvarezR** [comment]
@inse0918, @agrewalks would either of you be able to test and confirm that [the updated example](https://flow.byu.edu/FLOWPanel.jl/dev/examples/duct-aoasweep/) fixed the issue for you? (it might be good to update to the latest commit in the main branch)

(notice that the plots in the docs have not been updated)
